In [1]:
import os
from pathlib import Path
from PIL import Image


import torch
from torchvision import transforms
from torch.autograd import Variable

from tqdm import tqdm_notebook as tqdm

import sys
sys.path.insert(0, './model')

import model.classifier as classifier

In [2]:
base_data_folder = './data/data_clean'

# Define a global transformer to appropriately scale images and subsequently convert them to a Tensor.
img_size = 224
loader = transforms.Compose([
  transforms.Resize(img_size),
  transforms.CenterCrop(img_size),
  transforms.ToTensor(),
]) 

def load_image(filename):
    """
    Simple function to load and preprocess the image.

    1. Open the image.
    2. Scale/crop it and convert it to a float tensor.
    3. Convert it to a variable (all inputs to PyTorch models must be variables).
    4. Add another dimension to the start of the Tensor (b/c VGG expects a batch).
    5. Move the variable onto the GPU.
    """
    image = Image.open(filename).convert('RGB')
    image_tensor = loader(image).float()
    image_var = Variable(image_tensor).unsqueeze(0)
    return image_var

load_image('data/train_data/Drew_Barrymore/aligned_vgg_bfff48d47d2ec61e678fa23f885df73d.jpg')

tensor([[[[0.7451, 0.7608, 0.7843,  ..., 0.8941, 0.8941, 0.8941],
          [0.7490, 0.7647, 0.7882,  ..., 0.8941, 0.8941, 0.8941],
          [0.7569, 0.7725, 0.7922,  ..., 0.8941, 0.8941, 0.8941],
          ...,
          [0.6392, 0.5843, 0.5451,  ..., 0.6118, 0.6431, 0.6706],
          [0.6627, 0.6000, 0.5490,  ..., 0.5569, 0.5843, 0.6157],
          [0.6784, 0.6078, 0.5529,  ..., 0.5294, 0.5529, 0.5843]],

         [[0.6235, 0.6392, 0.6627,  ..., 0.8706, 0.8706, 0.8706],
          [0.6275, 0.6431, 0.6667,  ..., 0.8706, 0.8706, 0.8706],
          [0.6353, 0.6510, 0.6706,  ..., 0.8706, 0.8706, 0.8706],
          ...,
          [0.4745, 0.4196, 0.3804,  ..., 0.4627, 0.4941, 0.5216],
          [0.4980, 0.4353, 0.3843,  ..., 0.4078, 0.4353, 0.4667],
          [0.5137, 0.4431, 0.3882,  ..., 0.3804, 0.4039, 0.4353]],

         [[0.4392, 0.4549, 0.4824,  ..., 0.8784, 0.8784, 0.8784],
          [0.4431, 0.4588, 0.4863,  ..., 0.8784, 0.8784, 0.8784],
          [0.4510, 0.4667, 0.4902,  ..., 0

In [3]:
# Load Training Data

train_data_folder = base_data_folder + '/train_data'

class_to_name = [os.path.basename(f.path) for f in os.scandir(train_data_folder) if f.is_dir()]

train_id_to_file = {i : path 
                    for (i,path) in enumerate(Path(train_data_folder).glob("*/*.jpg"))}

train_id_to_class = {i : class_to_name.index(os.path.basename(os.path.dirname(str(path))))
                     for (i,path) in enumerate(Path(train_data_folder).glob("*/*.jpg"))}

train_ids = list(train_id_to_file.keys())

# Load Validation Data

val_data_folder = base_data_folder + '/eval_data'

val_id_to_file = {i : path 
                    for (i,path) in enumerate(Path(val_data_folder).glob("*/*.jpg"))}

val_id_to_class = {i : class_to_name.index(os.path.basename(os.path.dirname(str(path))))
                     for (i,path) in enumerate(Path(val_data_folder).glob("*/*.jpg"))}

val_ids = list(val_id_to_file.keys())


print("Classes:")
print(class_to_name)

print("\nTraining Set Size: %s" % len(train_ids))
print("\nValidation Set Size: %s" % len(val_ids))

print("\nSample Images:")
print(train_id_to_file[len(train_ids)-1])
print(class_to_name[train_id_to_class[len(train_ids)-1]])

load_image(train_id_to_file[len(train_ids)-1])

print(val_id_to_file[0])
print(class_to_name[val_id_to_class[0]])

load_image(val_id_to_file[0])


Classes:
['Zac_Efron', 'Cristiano_Ronaldo', 'Aaron_Eckhart', 'Clive_Owen', 'Alyssa_Milano', 'Christina_Ricci', 'Nicole_Richie', 'Brad_Pitt', 'Julia_Roberts', 'Drew_Barrymore']

Training Set Size: 1364

Validation Set Size: 100

Sample Images:
data/train_data/Drew_Barrymore/aligned_vgg_bfff48d47d2ec61e678fa23f885df73d.jpg
Drew_Barrymore
data/eval_data/Zac_Efron/aligned_vgg_0c5e844bc8df7d4742c0a6f790a7e6f1 4.46.24 PM.jpg
Zac_Efron


tensor([[[[0.4353, 0.4431, 0.4353,  ..., 0.0275, 0.0314, 0.0353],
          [0.4314, 0.4392, 0.4353,  ..., 0.0314, 0.0392, 0.0431],
          [0.4275, 0.4392, 0.4392,  ..., 0.0392, 0.0471, 0.0510],
          ...,
          [0.0431, 0.0471, 0.0510,  ..., 0.0157, 0.0157, 0.0157],
          [0.0314, 0.0353, 0.0392,  ..., 0.0157, 0.0157, 0.0157],
          [0.0275, 0.0314, 0.0353,  ..., 0.0157, 0.0157, 0.0157]],

         [[0.4118, 0.4196, 0.4118,  ..., 0.0275, 0.0314, 0.0353],
          [0.4078, 0.4157, 0.4118,  ..., 0.0314, 0.0392, 0.0431],
          [0.4039, 0.4157, 0.4157,  ..., 0.0392, 0.0471, 0.0510],
          ...,
          [0.0510, 0.0549, 0.0549,  ..., 0.0157, 0.0157, 0.0157],
          [0.0510, 0.0549, 0.0549,  ..., 0.0157, 0.0157, 0.0157],
          [0.0471, 0.0510, 0.0549,  ..., 0.0157, 0.0157, 0.0157]],

         [[0.2863, 0.2941, 0.2863,  ..., 0.0353, 0.0392, 0.0431],
          [0.2824, 0.2902, 0.2863,  ..., 0.0392, 0.0471, 0.0510],
          [0.2784, 0.2902, 0.2902,  ..., 0

In [4]:
model = classifier.FaceClassifier()

if torch.cuda.is_available():
    model = model.cuda()
    
print(model)

FaceClassifier(
  (model): Vgg_face_dag(
    (conv1_1): Conv2d(3, 64, kernel_size=[3, 3], stride=(1, 1), padding=(1, 1))
    (relu1_1): ReLU(inplace)
    (conv1_2): Conv2d(64, 64, kernel_size=[3, 3], stride=(1, 1), padding=(1, 1))
    (relu1_2): ReLU(inplace)
    (pool1): MaxPool2d(kernel_size=[2, 2], stride=[2, 2], padding=0, dilation=1, ceil_mode=False)
    (conv2_1): Conv2d(64, 128, kernel_size=[3, 3], stride=(1, 1), padding=(1, 1))
    (relu2_1): ReLU(inplace)
    (conv2_2): Conv2d(128, 128, kernel_size=[3, 3], stride=(1, 1), padding=(1, 1))
    (relu2_2): ReLU(inplace)
    (pool2): MaxPool2d(kernel_size=[2, 2], stride=[2, 2], padding=0, dilation=1, ceil_mode=False)
    (conv3_1): Conv2d(128, 256, kernel_size=[3, 3], stride=(1, 1), padding=(1, 1))
    (relu3_1): ReLU(inplace)
    (conv3_2): Conv2d(256, 256, kernel_size=[3, 3], stride=(1, 1), padding=(1, 1))
    (relu3_2): ReLU(inplace)
    (conv3_3): Conv2d(256, 256, kernel_size=[3, 3], stride=(1, 1), padding=(1, 1))
    (relu3_3):

In [5]:
# TODO - Fine-tuning

# Load Training Images and Labels

print('Loading training images...')

#train_ids = train_ids[:50]

images = Variable(torch.zeros((len(train_ids),3,img_size,img_size)))
labels = Variable(torch.zeros(len(train_ids)).long())

for i,train_id in enumerate(tqdm(train_ids)):
    # Prepare the image tensors
    images[i] = load_image(train_id_to_file[train_id])
    
    # Prepare the labels
    labels[i] = train_id_to_class[train_id]

# Load Validation Images and Labels

print('Loading validation images...')

val_images = Variable(torch.zeros((len(val_ids),3,img_size,img_size)))
val_labels = Variable(torch.zeros(len(val_ids)).long())

for i,val_id in enumerate(tqdm(val_ids)):
    # Prepare the image tensors
    val_images[i] = load_image(val_id_to_file[val_id])
    
    # Prepare the labels
    val_labels[i] = val_id_to_class[val_id]
    
X = images
y = labels

X_val = val_images
y_val = val_labels

print('Fine-tuning the model...')

model.tune(X, y, X_val, y_val)

print('Saving the model...')

filename = 'model/tuned_classifier.pth'
torch.save(model.state_dict(), filename)

print('Model saved as %s' % filename)

Loading training images...



Loading validation images...



Fine-tuning the model...


KeyboardInterrupt: 

In [6]:
images = Variable(torch.zeros((1,3,img_size,img_size)))
images[0] = load_image(train_id_to_file[0])
x = images

print(x.shape)
print(x[0])

activations = model.get_activations(x)

print(activations)

torch.Size([1, 3, 224, 224])
tensor([[[0.2588, 0.2627, 0.2667,  ..., 0.2784, 0.2745, 0.2706],
         [0.2471, 0.2510, 0.2549,  ..., 0.2902, 0.2902, 0.2863],
         [0.2314, 0.2353, 0.2392,  ..., 0.3059, 0.3059, 0.3020],
         ...,
         [0.1333, 0.1373, 0.1412,  ..., 0.1765, 0.1922, 0.2039],
         [0.1647, 0.1647, 0.1647,  ..., 0.1490, 0.1569, 0.1608],
         [0.1529, 0.1569, 0.1569,  ..., 0.1451, 0.1451, 0.1490]],

        [[0.1765, 0.1804, 0.1843,  ..., 0.2000, 0.1961, 0.1922],
         [0.1647, 0.1686, 0.1725,  ..., 0.2118, 0.2118, 0.2078],
         [0.1490, 0.1529, 0.1569,  ..., 0.2275, 0.2275, 0.2235],
         ...,
         [0.0706, 0.0745, 0.0784,  ..., 0.1412, 0.1569, 0.1686],
         [0.1020, 0.1020, 0.1020,  ..., 0.1137, 0.1216, 0.1255],
         [0.0902, 0.0941, 0.0941,  ..., 0.1098, 0.1098, 0.1137]],

        [[0.1961, 0.2000, 0.2039,  ..., 0.2078, 0.2039, 0.2000],
         [0.1843, 0.1882, 0.1922,  ..., 0.2196, 0.2196, 0.2157],
         [0.1686, 0.1725, 0.1

tensor([[[[0.2588, 0.2627, 0.2667,  ..., 0.2784, 0.2745, 0.2706],
          [0.2471, 0.2510, 0.2549,  ..., 0.2902, 0.2902, 0.2863],
          [0.2314, 0.2353, 0.2392,  ..., 0.3059, 0.3059, 0.3020],
          ...,
          [0.1333, 0.1373, 0.1412,  ..., 0.1765, 0.1922, 0.2039],
          [0.1647, 0.1647, 0.1647,  ..., 0.1490, 0.1569, 0.1608],
          [0.1529, 0.1569, 0.1569,  ..., 0.1451, 0.1451, 0.1490]],

         [[0.1765, 0.1804, 0.1843,  ..., 0.2000, 0.1961, 0.1922],
          [0.1647, 0.1686, 0.1725,  ..., 0.2118, 0.2118, 0.2078],
          [0.1490, 0.1529, 0.1569,  ..., 0.2275, 0.2275, 0.2235],
          ...,
          [0.0706, 0.0745, 0.0784,  ..., 0.1412, 0.1569, 0.1686],
          [0.1020, 0.1020, 0.1020,  ..., 0.1137, 0.1216, 0.1255],
          [0.0902, 0.0941, 0.0941,  ..., 0.1098, 0.1098, 0.1137]],

         [[0.1961, 0.2000, 0.2039,  ..., 0.2078, 0.2039, 0.2000],
          [0.1843, 0.1882, 0.1922,  ..., 0.2196, 0.2196, 0.2157],
          [0.1686, 0.1725, 0.1765,  ..., 0

In [8]:
print(activations.shape)

(1, 4096)
